COUNTRY_VAT_RATES = {
  "Austria": 20,
  "Belgium": 21,
  "Bulgaria": 20,
  "Croatia": 25,
  "Cyprus": 19,
  "Czech Republic": 21,
  "Denmark": 25,
  "Estonia": 22,
  "Finland": 24,
  "France": 20,
  "Germany": 19,
  "Greece": 24,
  "Hungary": 27,
  "Ireland": 23,
  "Italy": 22,
  "Latvia": 21,
  "Lithuania": 21,
  "Luxembourg": 17,
  "Malta": 18,
  "Netherlands": 21,
  "Poland": 23,
  'Portugal': 23,
  "Romania": 19,
  "Slovakia": 20,
  "Slovenia": 22,
  "Spain": 21,
  "Sweden": 25,
}.freeze

EU_COUNTRIES = COUNTRY_VAT_RATES.keys.freeze